cookbook/urls.py
from django.urls import path

from . import views

app_name = 'cookbook'
urlpatterns = [
    path('', views.index, name='index')
]

food_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('cookbook/', include('cookbook.urls'), name='cookbook'),
    path('restaurants/', include('restaurants.urls'), name='restaurants'),
    path('h31mp/', include('h31mp.urls'), name='h31mp')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

h31mp/urls.py
from django.urls import path

from . import views

app_name = 'h31mp'
urlpatterns = [
    path('', views.index, name='index')
]

restaurants/urls.py
from django.urls import path

from . import views

app_name = 'restaurants'
urlpatterns = [
    path('', views.index, name='index'),
    path('statistics/', views.statistics, name='statistics'),
    path('api/statistics/data/', views.get_statistics_data, name='api-data'),
    path('<slug:url_name>/', views.details, name='details')
]

cookbook/models.py
import os
import datetime

from pathlib import Path
from image_cropping import ImageRatioField

from django.db import models


def picture_file_name(instance, filename):
    ext = Path(filename).suffix
    name = instance.recipe_name + ext
    return os.path.join('food_pictures', name)


class Cuisine(models.Model):
    """ Represents a cuisine (e.g. Italian, Seafood, etc) """
    cuisine_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.cuisine_name


class Category(models.Model):
    """ Represents a category or cooking technique (e.g. braise)"""
    category_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.category_name


class Ingredient(models.Model):
    """ Represents a main ingredient used in a recipe """
    ingredient_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.ingredient_name


class Recipe(models.Model):
    """
    Django class representing all relevant information for a recipe.
    """
    recipe_name  = models.CharField(max_length=100)
    picture      = models.ImageField(blank=True, upload_to=picture_file_name)
    cropping     = ImageRatioField('picture', '1000x1000', size_warning=True)

    desc_summary = models.TextField("Description Summary", default="", blank=True)
    text_ingred  = models.TextField("Ingredients List", default="", blank=True)
    instructions = models.TextField("Instructions", default="", blank=True)
    notes        = models.TextField("Notes and Tips", default="", blank=True)
    personal_log = models.TextField("Personal Notes", default="", blank=True)

    cuisines    = models.ManyToManyField(to=Cuisine, blank=True)
    ingredients = models.ManyToManyField(to=Ingredient, blank=True)
    active_time = models.DurationField(default=datetime.timedelta())
    total_time  = models.DurationField(default=datetime.timedelta())
    categories  = models.ManyToManyField(to=Category, blank=True)

    last_cook_time = models.DateField()
    featured = models.BooleanField(default=False)
    url_name = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.recipe_name

cookbook/forms.py
from django import forms
from .models import Ingredient, Category


class RecipeChangeListForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
                         queryset=Category.objects.all(),
                         required=True
                 )

cookbook/views.py
import os
import datetime

from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.template import loader
from django.http import HttpResponse
from .models import Recipe, Category, Ingredient, Cuisine

from django.core.paginator import Paginator


def filter_recipes(request):
    recipe_set = Recipe.objects.order_by('recipe_name')

    # Type filtering (Featured, Recent, Short Time, Long Time)
    type_filter = request.GET.get('type', '')
    if type_filter:
        if type_filter == 'recent':
            recipe_set = recipe_set.order_by('-last_cook_time')[:25]
        elif type_filter == 'featured':
            recipe_set = recipe_set.filter(featured=True)
        elif type_filter == 'short-time':
            recipe_set = recipe_set.order_by('total_time').filter(
                                    total_time__lte=datetime.timedelta(hours=1))
        elif type_filter == 'long-time':
            recipe_set = recipe_set.order_by('-total_time').filter(
                                    total_time__gte=datetime.timedelta(hours=1))

    # Cuisine filtering
    cuisine_filter = request.GET.get('cuisine', '')
    if cuisine_filter:
        recipe_set = recipe_set.filter(cuisines__cuisine_name__contains=cuisine_filter)

    # Category filtering
    category_filter = request.GET.get('category', '')
    if category_filter:
        recipe_set = recipe_set.filter(categories__category_name__contains=category_filter)

    # Main Ingredient filter
    ingredient_filter = request.GET.get('ingredient', '')
    if ingredient_filter:
        recipe_set = recipe_set.filter(ingredients__ingredient_name__contains=ingredient_filter)

    return recipe_set


def index(request):
    recipes_to_display = filter_recipes(request)
    template = loader.get_template('cookbook/index.html')
    cuisines = Cuisine.objects.order_by('cuisine_name')
    categories = Category.objects.order_by('category_name')
    main_ingredients = Ingredient.objects.order_by('ingredient_name')

    # Pagination
    paginator = Paginator(recipes_to_display, 25)
    page_number = request.GET.get("page")
    if page_number is None:
        page_number = 1
    recipes_to_display_paginated = paginator.get_page(page_number)
    page_range = paginator.get_elided_page_range(page_number, on_each_side=3, on_ends=1)

    context = {
        'recipes_to_display': recipes_to_display_paginated,
        'current_page_number': int(page_number),
        'page_range': page_range,
        'cuisines': cuisines,
        'categories': categories,
        'main_ingredients': main_ingredients
    }
    return HttpResponse(template.render(context))


def details(request, url_name):
    recipe = get_object_or_404(Recipe, url_name=url_name)
    template = loader.get_template('cookbook/details.html')
    context = {'url_name': url_name, 'recipe': recipe}
    return HttpResponse(template.render(context))

cookbook/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name='description' content="{% block meta-description %}{% endblock %}">
        <meta name='keywords' content="{% block meta-keywords%}{% endblock %}">

        <title>{% block headtitle %}{% endblock %}</title>

        <link rel='icon' href="{% static 'thumbnail.jpg' %}">

        <!--Social media graph information-->
        <meta property='og:url' content="http://{{site.domain}}{{request.path}}">
        <!--
        <meta property='og:site_name' content="">
        <meta property='og:image' content="">
        <meta property='og:title' content="">
        <meta property='og:description' content="">
        <meta property='og:type' content='website'>-->

        <!-- Bootstrap CSS -->
        <link rel='stylesheet' href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Font CSS -->
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
        <link rel='stylesheet' href="{% static 'default.css' %}">

        <!-- JAVASCRIPT -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- Chart.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>

        <!-- Extend header settings in children files -->
        <!-- NOTE: personal CSS files should be included in here -->
        {% block extrahead %}{% endblock %}
    </head>

    <body id="{% block bodyid %}page{% endblock %}" class="{% block bodyclass %}default {%endblock %}">
        {% include "navbar.html" %}

        {% block main_content %}
        {% endblock %}

        <!-- Footer, for additional space at the bottom -->
        <br>
        {% block extrascript %}{% endblock %}

        <!-- JQuery block for visualization display -->
        <script>
            $(document).ready(function() {
                {% block jquery %}{% endblock %}
            })
        </script>
    </body>
</html>

cookbook/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: rgb(65, 65, 65);">
    <a class="navbar-brand" href="{% url 'index' %}">Brian Xie</a>
	<button class="navbar-toggler" type='button' data-toggle='collapse' data-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse w-100 order-3 dual-collapse2" id='navbarNav'>
		<ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class='nav-link' href="{% url 'cookbook:index' %}">Cookbook</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'restaurants:index' %}">Restaurants</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'restaurants:statistics' %}">Visualizations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'h31mp:index' %}">H31MP</a>
            </li>
		</ul>
	</div>
</nav>